### ISSUE TITLE
Spelling check under 3.11 table

### ISSUE THREAD

**Issue by amandacaster** [threefoldfoundation/info_cloud_production#11]
As you see below the spelling for **which** needs to be changed 

![image](https://github.com/threefoldfoundation/info_cloud_production/assets/88147124/72dc967b-82a7-4cda-928c-40f3cd15f95f)

Was not able to create a branch and PR to make the amendments myself.

**Comment by amandacaster** [comment]
[PR](https://github.com/threefoldfoundation/info_cloud_production/pull/13) created.

**Comment by despiegk** [comment]
still relevant?
close all other PR

**Comment by samtaggart** [comment]
@sasha-astiadi Can you please check on this and close the issue?

**Comment by sasha-astiadi** [comment]
closed
